export const products = [
    {
        id: 1,
        image: "/products/product1.jpg",
        name: "Basic Cotton T-Shirt",
        price: "$19.90",
        discount: "$12.90",
        section: "Clothing",
        department: "Unisex",
        rating: 5,
        reviewCount: 124,
        stockCount: 56,
        description: "Yumuşak pamuk, regular fit, günlük kullanım için nefes alır.",
        colorOptions: ["bg-[#111827]", "bg-[#F59E0B]", "bg-[#10B981]", "bg-[#3B82F6]"],
        sellCount: 980
    },
    {
        id: 2,
        image: "/products/product2.jpg",
        name: "Slim Fit Jeans",
        price: "$39.90",
        discount: null,
        section: "Clothing",
        department: "Men",
        rating: 4,
        reviewCount: 87,
        stockCount: 32,
        description: "Esnek denim, dar kesim, orta bel.",
        colorOptions: ["bg-[#1F2937]", "bg-[#374151]"],
        sellCount: 420
    },
    {
        id: 3,
        image: "/products/product3.jpg",
        name: "Oversize Hoodie",
        price: "$49.90",
        discount: "$39.90",
        section: "Clothing",
        department: "Unisex",
        rating: 5,
        reviewCount: 210,
        stockCount: 18,
        description: "Kanguru cepli, içi polar, oversize kalıp.",
        colorOptions: ["bg-[#111827]", "bg-[#E5E7EB]", "bg-[#EF4444]"],
        sellCount: 1100
    },
    {
        id: 4,
        image: "/products/product4.jpg",
        name: "Midi Wrap Dress",
        price: "$59.90",
        discount: "$44.90",
        section: "Clothing",
        department: "Women",
        rating: 4.5,
        reviewCount: 64,
        stockCount: 25,
        description: "Sargı kesim, v yaka, akıcı kumaş.",
        colorOptions: ["bg-[#DB2777]", "bg-[#111827]", "bg-[#F59E0B]"],
        sellCount: 370
    },
    {
        id: 5,
        image: "/products/product5.jpg",
        name: "Athletic Joggers",
        price: "$34.90",
        discount: null,
        section: "Clothing",
        department: "Unisex",
        rating: 4,
        reviewCount: 95,
        stockCount: 62,
        description: "Lastikli paça, esnek bel, spor kullanım.",
        colorOptions: ["bg-[#111827]", "bg-[#6B7280]"],
        sellCount: 520
    },
    {
        id: 6,
        image: "/products/product6.jpg",
        name: "Linen Short Sleeve Shirt",
        price: "$29.90",
        discount: "$24.90",
        section: "Clothing",
        department: "Men",
        rating: 4,
        reviewCount: 58,
        stockCount: 41,
        description: "%100 keten, serin tutar, rahat kalıp.",
        colorOptions: ["bg-[#F3F4F6]", "bg-[#93C5FD]", "bg-[#10B981]"],
        sellCount: 260
    },
    {
        id: 7,
        image: "/products/product7.jpg",
        name: "High-Rise Mom Jeans",
        price: "$44.90",
        discount: "$34.90",
        section: "Clothing",
        department: "Women",
        rating: 5,
        reviewCount: 133,
        stockCount: 29,
        description: "Yüksek bel, rahat kalça, düz paça.",
        colorOptions: ["bg-[#1F2937]", "bg-[#93C5FD]"],
        sellCount: 690
    },
    {
        id: 8,
        image: "/products/product8.jpg",
        name: "Puffer Jacket",
        price: "$79.90",
        discount: "$59.90",
        section: "Clothing",
        department: "Unisex",
        rating: 4,
        reviewCount: 77,
        stockCount: 12,
        description: "Hafif dolgulu, suya dayanıklı dış yüzey.",
        colorOptions: ["bg-[#111827]", "bg-[#2563EB]", "bg-[#D1D5DB]"],
        sellCount: 340
    },
    {
        id: 9,
        image: "/products/product9.jpg",
        name: "Ribbed Knit Sweater",
        price: "$39.90",
        discount: null,
        section: "Clothing",
        department: "Women",
        rating: 4,
        reviewCount: 68,
        stockCount: 44,
        description: "Triko, fitilli doku, yuvarlak yaka.",
        colorOptions: ["bg-[#D1D5DB]", "bg-[#F59E0B]", "bg-[#111827]"],
        sellCount: 300
    },
    {
        id: 10,
        image: "/products/product10.jpg",
        name: "Classic Polo Shirt",
        price: "$24.90",
        discount: "$19.90",
        section: "Clothing",
        department: "Men",
        rating: 4,
        reviewCount: 120,
        stockCount: 73,
        description: "Pike kumaş, düğmeli yaka, regular fit.",
        colorOptions: ["bg-[#3B82F6]", "bg-[#10B981]", "bg-[#111827]"],
        sellCount: 840
    },
    {
        id: 11,
        image: "/products/product11.jpg",
        name: "Pleated Midi Skirt",
        price: "$36.90",
        discount: null,
        section: "Clothing",
        department: "Women",
        rating: 4,
        reviewCount: 49,
        stockCount: 27,
        description: "Pileli, hafif kumaş, elastik bel.",
        colorOptions: ["bg-[#F59E0B]", "bg-[#111827]", "bg-[#E5E7EB]"],
        sellCount: 210
    },
    {
        id: 12,
        image: "/products/product12.jpg",
        name: "Active Dry-Fit Tee",
        price: "$22.90",
        discount: "$16.90",
        section: "Clothing",
        department: "Unisex",
        rating: 5,
        reviewCount: 155,
        stockCount: 90,
        description: "Hızlı kuruyan, ter tutmaz, antrenman için.",
        colorOptions: ["bg-[#3B82F6]", "bg-[#10B981]", "bg-[#111827]"],
        sellCount: 1200
    },
    {
        id: 13,
        image: "/products/product13.jpg",
        name: "Denim Jacket",
        price: "$54.90",
        discount: "$44.90",
        section: "Clothing",
        department: "Unisex",
        rating: 4,
        reviewCount: 61,
        stockCount: 21,
        description: "Klasik kesim, sert denim, düğmeli ön.",
        colorOptions: ["bg-[#1F2937]", "bg-[#93C5FD]"],
        sellCount: 480
    },
    {
        id: 14,
        image: "/products/product14.jpg",
        name: "Crew Socks 3-Pack",
        price: "$12.90",
        discount: null,
        section: "Clothing",
        department: "Unisex",
        rating: 4,
        reviewCount: 34,
        stockCount: 140,
        description: "Yastıklamalı taban, nefes alan pamuk karışım.",
        colorOptions: ["bg-[#111827]", "bg-[#FFFFFF]", "bg-[#D1D5DB]"],
        sellCount: 950
    },
    {
        id: 15,
        image: "/products/product15.jpg",
        name: "Boxy Crop Top",
        price: "$17.90",
        discount: "$12.90",
        section: "Clothing",
        department: "Women",
        rating: 4,
        reviewCount: 42,
        stockCount: 38,
        description: "Kısa boy, boxy kalıp, elastik pamuk.",
        colorOptions: ["bg-[#EF4444]", "bg-[#111827]", "bg-[#FDE68A]"],
        sellCount: 260
    },
    {
        id: 16,
        image: "/products/product16.jpg",
        name: "Chino Pants",
        price: "$39.90",
        discount: null,
        section: "Clothing",
        department: "Men",
        rating: 4,
        reviewCount: 73,
        stockCount: 47,
        description: "Düz kesim, streçli chino kumaş.",
        colorOptions: ["bg-[#F3F4F6]", "bg-[#111827]", "bg-[#10B981]"],
        sellCount: 510
    },
    {
        id: 17,
        image: "/products/product17.jpg",
        name: "Thermal Long Sleeve",
        price: "$24.90",
        discount: "$18.90",
        section: "Clothing",
        department: "Unisex",
        rating: 5,
        reviewCount: 66,
        stockCount: 35,
        description: "Termal doku, sıcak tutar, katmanlama için ideal.",
        colorOptions: ["bg-[#6B7280]", "bg-[#111827]"],
        sellCount: 300
    },
    {
        id: 18,
        image: "/products/product18.jpg",
        name: "Raincoat Shell",
        price: "$69.90",
        discount: "$54.90",
        section: "Clothing",
        department: "Unisex",
        rating: 4,
        reviewCount: 52,
        stockCount: 16,
        description: "Su geçirmez dış katman, ayarlanabilir kapüşon.",
        colorOptions: ["bg-[#2563EB]", "bg-[#111827]", "bg-[#D1D5DB]"],
        sellCount: 190
    },
    {
        id: 19,
        image: "/products/product19.jpg",
        name: "Yoga Leggings",
        price: "$29.90",
        discount: "$22.90",
        section: "Clothing",
        department: "Women",
        rating: 5,
        reviewCount: 141,
        stockCount: 58,
        description: "Yüksek bel, 4-yön esneme, dikişsiz konfor.",
        colorOptions: ["bg-[#111827]", "bg-[#10B981]", "bg-[#A78BFA]"],
        sellCount: 760
    },
    {
        id: 20,
        image: "/products/product20.jpg",
        name: "Classic Cardigan",
        price: "$42.90",
        discount: null,
        section: "Clothing",
        department: "Unisex",
        rating: 4,
        reviewCount: 39,
        stockCount: 22,
        description: "İnce triko, düğmeli, katmanlamaya uygun.",
        colorOptions: ["bg-[#D1D5DB]", "bg-[#111827]", "bg-[#F59E0B]"],
        sellCount: 230
    }
];
